### ISSUE TITLE
Encountered error E: You must put some 'deb-src' URIs in your sources.list

### ISSUE THREAD

**Issue by haochenuw** [sev-step/sev-step#1]
The above error occurred when executing 
sudo apt-get build-dep ovmf qemu-system-x86

Could someone advise on how to unblock and reproduce the build? The OS I am on is Ubuntu 22.04

**Comment by its-luca** [comment]
Hi @haochenuw 

thanks for you interest in sev step.
You need open `/etc/apt/sources.list` and uncomment the `deb-src` entries. Afterwards execute `sudo apt update`. Then everything should work as expected. Feel free to reach out if you encounter other issues.

**Comment by its-luca** [comment]
I assume this solved your problem. If not, feel free to re-open the issue
