### ISSUE TITLE
SEV-SNP: failed to INIT error 0x3;   SEV: failed to INIT error 0x1

### ISSUE THREAD

**Issue by silver-airship** [sev-step/sev-step#3]
These messages are from dmesg.
But each ASIDs nums still be showen.
BTW, the RMP table output is correct.

**Comment by silver-airship** [comment]
This happened only if i start sev-step kernel **(recovery mode)** in grub, and then resume normal boot.
If i choose no-recovery mode, `efi: Failed to lookup EFI memory descriptor for 0x00000000ab54f00`

**Comment by silver-airship** [comment]
OMG, the failed to INIT error also output in grub recovery root shell, before i resume normal boot.

**Comment by its-luca** [comment]
This seems like a general problem with enabling SNP on the machine. These errors can be quite hard to debug.
I would suggest that you open an issue in the official (SEV Repo)[https://github.com/AMDESE/AMDSEV] . For the issue to be processed it might be a good idea to first try the manual/software versions in their repo to setup a SEV VM

**Comment by silver-airship** [comment]
In sev-step kernel, ccp shows that
`SEV-SNP: failed to INIT error 0x3`
`SEV: failed to INIT error 0x1`
But when I simply switch to snp-host kernel, ccp shows that
`sev enabled`
`SEV API:1.52 build:4`
`SEV-SNP API:1.52 build:4`
So I don't know what the problem is right now.

**Comment by silver-airship** [comment]
Maybe it because `sev_cmd_buffer_len(cmd)` will return 0 when `cmd = SEV_CMD_SNP_INIT		= 0x81`?
I believe my hardware and bios config is correct, as well as **API:1.52 build:4**.

**Comment by its-luca** [comment]
Could you post the exact kernel you are using as "snp-host kernel"?  Is it https://github.com/AMDESE/AMDSEV/tree/snp-latest ?

**Comment by silver-airship** [comment]
Yes, I can run both snp host and snp guest by git clone [](https://github.com/AMDESE/AMDSEV/tree/snp-latest).

**Comment by silver-airship** [comment]
Yes, I can run both snp host and snp guest by git clone [https://github.com/AMDESE/AMDSEV/tree/snp-latest](https://github.com/AMDESE/AMDSEV/tree/snp-latest)
I tried SEV firmware 1.52 and 1.54. Maybe only 1.51 can INIT the sev-step kernel?
I tried [https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amd/amd_sev_fam19h_model0xh.sbin](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amd/amd_sev_fam19h_model0xh.sbin), But it shows 1.52
Could you provide `1.51.sbin` for me?

**Comment by its-luca** [comment]
I guess you are onto something. There probably is some dependency between the Kernel version and the firmware version. The kernel that sev step is based on is already a bit dated, as porting to newer kernel versions is quite tedious.

Unfortunately I am using the firmware version that comes with my BIOS, which is `SEV-SNP API:1.49 build:3`, and thus cannot provide you with the .sbin file :(. You can try which version your BIOS ships by deleting the firmware file (and reboot).

The closest version that I could find online is https://github.com/lumag/linux-firmware/blob/7160358442374984fe61b448bc86b97c9b21bf09/amd/amd_sev_fam19h_model0xh.sbin . Could you try if that works?

**Comment by silver-airship** [comment]
Unfortunately, the firmware version is still 1.52 after using [https://github.com/lumag/linux-firmware/blob/7160358442374984fe61b448bc86b97c9b21bf09/amd/amd_sev_fam19h_model0xh.sbin](https://github.com/lumag/linux-firmware/blob/7160358442374984fe61b448bc86b97c9b21bf09/amd/amd_sev_fam19h_model0xh.sbin) .

Maybe the latest version of bios and .sbin will  be selected during initialization.

I can change my bios version by using BMC. I'm trying to find a suitable `bios.ROM` file.

Our motherboard models should be different, i'm trying different bios version from [https://servers.asus.com.cn/products/Servers/Server-Motherboards/KRPA-U16/#Resources](https://servers.asus.com.cn/products/Servers/Server-Motherboards/KRPA-U16/#Resources)

**Comment by its-luca** [comment]
I am assuming others will also run into these issues. I will look into updating the kernel version of sev step.

**Comment by silver-airship** [comment]
The .sbin you provide is 1.42, which also can't INIT sev-step kernel.

I tried 1.40 1.52 via bios and 1.42 1.51 1.54 via .sbin .

But unfortunately, none of them can INIT sev-step kernel. A #PF will rise or INIT error code will be shown by ccp.

Looking forward to your update and please let the sev-step kernel dependent on an available SEV firmware, such as 1.54 .

**Comment by its-luca** [comment]
I just wanted to let you know that I have not forgotten this issue. I should have some time to look into this next week.

**Comment by silver-airship** [comment]
Ok, thank you very much !

**Comment by dawsonme** [comment]
Hi @its-luca ，i am facing the same issue, and my motherboard is the same as yours (i.e., a Dell PowerEdge R6515). Could you provide your bios version and the firmware 1.49.sbin for me?  I plan to change my SEV firmware from 1.52.sbin to 1.49.sbin to see if it works. Thanks!

**Comment by its-luca** [comment]
I am mostly done updating SEV-Step to a more recent kernel version. On my machine this allowed me to use the most recent firmware. While everything seems to work I want to do some more testing on Monday.  Afterwards, I will update the gitmodules+build scripts in this repo.  However, you can already get the updated kernel at https://github.com/sev-step/sev-step-host-kernel/tree/sm-sev-step-main-5-19-kern-release and the corresponding updated userspace library at https://github.com/sev-step/sev-step-userland  .

**Comment by its-luca** [comment]
I also updated this repo now. Please have a look and let me know if you run into any issues.

**Comment by silver-airship** [comment]
ok, let me have a try.

**Comment by silver-airship** [comment]
`dmesg` shows the correct ccp messages! 
I think we should close this issue now.
I will create another issue if  other errors occur during Create and Run a SEV VM or End to end tests.
Once again, my heartfelt thanks.
