### ISSUE TITLE
Booting from Hard Disk...     This message lasted more than 24 hours

### ISSUE THREAD

**Issue by silver-airship** [sev-step/sev-step#4]
After the VM OS successfully installed, I killed qemu.
Next command i used is `qemu-system-x86_64 -hda ../../../../VM_DISK.qcow2 -vnc :1`
Is it correct to start the VM again?

**Comment by its-luca** [comment]
Yes, after installing the OS, you should be able to start the VM again. However,
try using the `launch-qemu.sh` script from the repo, i.e. `sudo ./launch-qemu.sh -hda  ../../../../VM_DISK.qcow2 -vnc :1 `. Do you get any relevant output when connecting via vnc?

**Comment by silver-airship** [comment]
yes i see grub shell via vnc, but how can i linux the kernel and initrd the img?
I can't find any boot directory by using `ls`

**Comment by silver-airship** [comment]
I find a grub shell and linux the kernel, initrd the img, and then boot.
But there is only a (initramfs).

**Comment by its-luca** [comment]
This sounds like sth. went wrong installing the OS in the VM. I would suggest you try that part again. This should be unrelated to any sev step or sev problems

**Comment by silver-airship** [comment]
I change the iso file from `Ubuntu 22.10 amd64, Server` to `Ubuntu 22.10 amd64, Desktop LiveDVD`.
Installation is successful.
